### ISSUE TITLE
Suggested minor tweaks to the HOURv3 smart contract

### ISSUE THREAD

**Issue by ECBSJ** [happyhourDAO/Happy-Hour-Protocol-Engine#3]
In development of the front-end app, a few minor suggestions to the HOURv3 smart contract needs to be addressed:

1. A `public view` getter function needs to be available and present, as shown below:

```
function totalPDE() public view returns (uint) {
        return pdes.length;
    }
```

Retrieving PDEs by address on the front end will consist of mapping a new array from an initial array. The initial array will need to have a limited length in the `for` loop as show below:

```
  for (let i = 0; i < currentTotalPDE; i++) {
    await hour_contract.PDEtoOwner(i).then(res => {
      if (res == address) {
        myArray.push(i)
      }
    })
  }
```

2. A PDE identifier needs to be emitted during the `endHOURresults` event, as shown below:

```
event endHOURresults(uint hoursSpentDrinking, uint HOURearned, uint PDEcommissionEarned, uint PDEindex);
```

This will assist retrieving historical HOUR commissions earned by PDE on the front end. For this, the index of the PDE from the `pdes` public array needs to be emitted. 

3. The `else` clause of the `startHOUR` function to be omitted and the variable of `validPDE` to be refactored into a boolean:

```
        bool validPDE = false;

        for (uint i = 0; i < pdes.length; i++) {
            if (pdes[i]._PDEid == _PDEid && pdes[i]._accessCode == _accessCode) {
                validPDE = true;
            }
        }

        require(validPDE == true);
```

Unexpected errors occurred in the previous contract forcing a `execution revert` error when `pdes.length` was greater than 1.

**Next Steps**

A final review will be conducted and determination of versioning will be decided. A push of the new contract will happen soon.

**Comment by jiamijiang** [comment]
After an internal live deliberation on Discord chat within the community, a unanimous agreement was made to push these changes live to the repo.

This issue will now be closed.
